stages:
  - test
  - build

before_script:
  - pip install Sphinx snakehouse Cython satella case-converter nose2 yaml
  - python compile_stanag.py

image: smokserwis/build:python3

unittest:
  stage: test
  script:
    - python setup.py install
    - nose2


build:
  stage: build
  script:
    - strip-docs .
    - python setup.py bdist_wheel
    - cp dist/*.whl .
    - doctor-wheel *.whl
  artifacts:
    paths:
      - "*.whl"

pages:
  stage: build
  variables:
    DEBUG: "1"
  script:
    - python setup.py install
    - cd docs
    - make html
    - cd ..
    - cp -rf docs/_build/html public
  artifacts:
    paths:
      - "public"
